version: '2'
services:
  weather_exporter:
    build: .
    image: ${ORGANIZATION}/${CONTAINER}:${VERSION}
    container_name: ${CONTAINER}
    ports:
      - ${ENDPOINT_PORT}:${ENDPOINT_PORT}
    environment:
      - DARK_SKY_API_KEY=${DARK_SKY_API_KEY}
      - ENDPOINT_PORT=${ENDPOINT_PORT}
      - SCRAPE_INTERVAL=${SCRAPE_INTERVAL}
      - CITIES=${CITIES}
    volumes:
      - ./src/weather_exporter:/weather_exporter
      
